# Generated by Django 5.1.5 on 2025-02-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliquepay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://storage.cloud.google.com/cliquepay_profile_photo_bucket/Default_pfp.jpg'),
        ),
    ]
