# Generated by Django 5.1.6 on 2025-03-22 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliquepay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='cliquepay.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to='cliquepay.user')),
            ],
            options={
                'db_table': 'expense_splits',
                'unique_together': {('expense', 'user')},
            },
        ),
    ]
