# Generated by Django 5.1.6 on 2025-03-17 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliquepay', '0002_alter_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cliquepay.user')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='cliquepay.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to='cliquepay.user')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
    ]
