# Generated by Django 5.1.6 on 2025-03-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliquepay', '0002_expensesplit'),
        ('cliquepay', '0003_directmessage_groupmessage'),
    ]

    operations = [
    ]
